### ISSUE TITLE
SASL documentation is wrong

### ISSUE THREAD

**Issue by SnoopJ** [sopel-irc/sopel.chat#31]
The IRCv3 appendix contains a [section on SASL authentication](https://sopel.chat/appendix/ircv3/#sasl-authentication) that refers to a non-existent field `core.sasl_password`. Offending section states

> If the server supports SASL authentication, and a sasl_password value is set in the [core] section of the config file, Sopel will attempt to authenticate with it

but this isn't true. The [actual SASL logic](https://github.com/sopel-irc/sopel/blob/d7a538d022706fbab0cde800610554fba578f553/sopel/coretasks.py#L1127-L1136) checks for `core.auth_method` or `core.server_auth_method`

Discovered because the newly-formed Libera network has been [restricting some IP ranges to SASL-only](https://libera.chat/guides/sasl#sasl-access-only-ip-ranges) to prevent abuse, and was confused because my Sopel instance wouldn't connect even when configured "correctly."

**Comment by dgw** [comment]
You might note the warning box on that page:

![image](https://user-images.githubusercontent.com/164140/119211074-b412c100-ba75-11eb-9faf-50d00560774a.png)

Relevant configuration settings [were changed](https://github.com/sopel-irc/sopel/commit/db55dabc5703c31d3b09effc2fc58896a7455298) for Willie 5.2, long before I took over maintenance of the Sopel project—indeed before "Sopel" even existed—and the legacy setting names were deleted in 6.0.

We have focused most recent documentation efforts on the Sphinx side (what appears on the website under `/docs/`), and there you will find [a whole section on Authentication](https://sopel.chat/docs/configuration.html#authentication). A pull request to update some or all of the incorrect information would, of course, be most welcome, if you do not want to wait for the old wiki pages to get an overhaul sometime after we finalize Sopel 7.1.

**Comment by SnoopJ** [comment]
Aha, I was wondering. I opened a PR (#32)  for these anyhow, but maybe the box could also point the users towards the docs that are being more actively maintained (and/or a deprecation notice, if appropriate)

**Comment by dgw** [comment]
The box, too, is "a little outdated", haha. 😸 It's from a migration almost 2.5 years ago.

**Comment by SnoopJ** [comment]
> 
> 
> The box, too, is "a little outdated", haha. smile_cat It's from a migration almost 2.5 years ago.

Understandable! I most definitely read the _From version 4.1.0..._ part of that page, but apparently it didn't quiiiite sink in that I was using a **MUCH** more modern one. :sweat_smile:

Updated my PR to drop a link into the warning box in case anybody else lands on that page looking for what I was. It's the second result for me when searching _"Sopel SASL"_, where the first is the main page.
