### ISSUE TITLE
Outdated installation instructions

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel.chat#43]
```
$ git clone git://github.com/sopel-irc/sopel.git
Cloning into 'sopel'...
fatal: unable to connect to github.com:
github.com[0: 192.30.255.112]: errno=Connection timed out
```

This happens in two different Linux boxes and two different ISPs. I am using "Latest source" instructions from [sopel.chat/usage/installing](https://sopel.chat/usage/installing/).

_— originally reported by @antdude at sopel-irc/sopel#2517_

**Comment by dgw** [comment]
Note: The cause here is [GitHub permanently disabling plaintext `git://` protocol support](https://github.blog/2021-09-01-improving-git-protocol-security-github/) way back in March 2022. Our installation page hasn't caught up to that change, but the main repo's README did.

**Comment by antdude** [comment]
Thanks. I also noticed https://github.com/sopel-irc/sopel/blob/master/README.rst has v7.1.9 for the latest source's tarball link (https://github.com/sopel-irc/sopel/releases/latest). It goes to https://github.com/sopel-irc/sopel/releases/tag/v7.1.9, That should be at v8, right?

**Comment by dgw** [comment]
There is no _actual_ v8 yet, only latest source. But the latest-source archive link should be either removed (you're already on GitHub; just clone it) or updated to point the same place the site does (`https://github.com/sopel-irc/sopel/archive/refs/heads/master.zip`).

**Comment by dgw** [comment]
sopel-irc/sopel#2518 for that last bit
